"""
measure_o2_auth.py — O2 Multi-Layer Authentication Empirical Test
=================================================================

Tests all three authentication boundaries in MediSync:

  Boundary 1 — ESP32 device (X-Device-Secret header, local backend)
    Test A: No header          → expect 403
    Test B: Wrong secret        → expect 403
    Test C: Correct secret, no active patient → expect 400
             (auth passes; blocked by "no active patient" guard — proves auth works)

  Boundary 2 — Nurse login (IC + shared password, local backend)
    Test D: Wrong nurse password → expect 401

  Boundary 3 — Admin JWT (Supabase Auth, cloud backend)
    Test E: No Authorization header → expect 401
    Test F: Invalid JWT             → expect 401

Usage
-----
    python measure_o2_auth.py \\
        --device-secret <your-device-secret>

    python measure_o2_auth.py \\
        --device-secret esp32 \\
        --local-url  http://localhost:8000 \\
        --cloud-url  https://medisync-cloud-api-production.up.railway.app

    The --device-secret can also be set via DEVICE_SECRET env var or .env file.

Results are written to o2_auth_results.md in the project root.
"""

import argparse
import os
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

import requests

try:
    from dotenv import load_dotenv
    load_dotenv(Path(__file__).parent.parent / "backend" / "local" / ".env")
except ImportError:
    pass

LOCAL_API_DEFAULT = "http://localhost:8000"
CLOUD_API_DEFAULT = "https://medisync-cloud-api-production.up.railway.app"
HEALTH_URL_TMPL   = "{}/health"
OUTPUT_PATH       = Path(__file__).parent / "o2_auth_results.md"


def wait_for_backend(url: str, label: str, timeout: int = 30) -> bool:
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        try:
            r = requests.get(HEALTH_URL_TMPL.format(url), timeout=3)
            if r.status_code == 200:
                return True
        except requests.exceptions.RequestException:
            pass
        time.sleep(2)
    return False


def run_test(label: str, method: str, url: str, **kwargs) -> dict:
    t_start = time.monotonic()
    try:
        fn = getattr(requests, method)
        resp = fn(url, timeout=8, **kwargs)
        elapsed_ms = (time.monotonic() - t_start) * 1000
        return {
            "label":      label,
            "url":        url,
            "status":     resp.status_code,
            "elapsed_ms": round(elapsed_ms, 1),
            "error":      None,
        }
    except requests.exceptions.RequestException as exc:
        elapsed_ms = (time.monotonic() - t_start) * 1000
        return {
            "label":      label,
            "url":        url,
            "status":     None,
            "elapsed_ms": round(elapsed_ms, 1),
            "error":      str(exc),
        }


def evaluate(result: dict, expected_status: int) -> bool:
    return result["status"] == expected_status


def write_report(results: list[dict], expectations: list[int], now_str: str) -> None:
    lines = [
        "# O2 Authentication Boundary Test Results",
        "",
        f"Measured: {now_str}  ",
        "",
        "## Test Results",
        "",
        "| # | Boundary | Test | Expected | Got | Response (ms) | Pass? |",
        "|---|----------|------|----------|-----|---------------|-------|",
    ]

    boundaries = [
        "Device (X-Device-Secret)",
        "Device (X-Device-Secret)",
        "Device (X-Device-Secret)",
        "Nurse (IC + password)",
        "Admin JWT (cloud)",
        "Admin JWT (cloud)",
    ]

    all_pass = True
    for i, (r, expected, boundary) in enumerate(zip(results, expectations, boundaries), 1):
        got   = str(r["status"]) if r["status"] else f"ERR: {r['error'][:30]}"
        passed = evaluate(r, expected)
        if not passed:
            all_pass = False
        mark  = "✅" if passed else "❌"
        lines.append(
            f"| {i} | {boundary} | {r['label']} | {expected} | {got} | {r['elapsed_ms']} ms | {mark} |"
        )

    overall = "✅ ALL PASS" if all_pass else "❌ SOME FAILED"
    lines += [
        "",
        f"**Overall: {overall}**",
        "",
        "## Interpretation",
        "",
        "- Tests A & B confirm the device-secret guard rejects any request without or with wrong credentials.",
        "- Test C confirms auth *passes* with the correct secret: the 400 response comes from the 'no active patient' guard downstream — not from auth. This proves the boundary is enforced, not bypassed.",
        "- Test D confirms the nurse login rejects wrong passwords before any session is opened.",
        "- Tests E & F confirm the cloud admin API is fully inaccessible without a valid Supabase JWT.",
        "",
        "---",
        "_Generated by `measure_o2_auth.py`_",
    ]

    OUTPUT_PATH.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="O2 auth boundary test")
    parser.add_argument("--device-secret", default=os.getenv("DEVICE_SECRET", ""), help="Correct device secret")
    parser.add_argument("--local-url",  default=LOCAL_API_DEFAULT)
    parser.add_argument("--cloud-url",  default=CLOUD_API_DEFAULT)
    args = parser.parse_args()

    if not args.device_secret:
        print("[auth-test] ERROR: --device-secret is required (or set DEVICE_SECRET env var / .env)")
        sys.exit(1)

    print("[auth-test] O2 Multi-Layer Authentication Test")
    print(f"[auth-test] Local  API: {args.local_url}")
    print(f"[auth-test] Cloud  API: {args.cloud_url}\n")

    print("[auth-test] Checking local backend …")
    if not wait_for_backend(args.local_url, "local"):
        print("[auth-test] ❌ Local backend not reachable. Start it with: uvicorn main:app --port 8000")
        sys.exit(1)
    print("[auth-test] ✅ Local backend ready\n")

    dummy_reading = {"spo2": 97.5, "bpm": 72, "temperature": 36.6}

    tests = [
        # (label, method, url, kwargs, expected_status)
        (
            "No X-Device-Secret header",
            "post",
            f"{args.local_url}/api/readings",
            {"json": dummy_reading, "headers": {}},
            403,
        ),
        (
            "Wrong X-Device-Secret header",
            "post",
            f"{args.local_url}/api/readings",
            {"json": dummy_reading, "headers": {"X-Device-Secret": "WRONG_SECRET_12345"}},
            403,
        ),
        (
            "Correct secret, no active patient → 400 (auth passes)",
            "post",
            f"{args.local_url}/api/readings",
            {"json": dummy_reading, "headers": {"X-Device-Secret": args.device_secret}},
            400,
        ),
        (
            "Wrong nurse password → 401",
            "post",
            f"{args.local_url}/api/session/login",
            {"json": {"ic_number": "000000-00-0000", "password": "WRONG_NURSE_PW"}},
            401,
        ),
        (
            "Cloud GET /api/patients — no auth → 401",
            "get",
            f"{args.cloud_url}/api/patients",
            {},
            401,
        ),
        (
            "Cloud GET /api/patients — invalid JWT → 401",
            "get",
            f"{args.cloud_url}/api/patients",
            {"headers": {"Authorization": "Bearer totally.invalid.jwt"}},
            401,
        ),
    ]

    expectations = [t[4] for t in tests]
    results = []

    for label, method, url, kwargs, expected in tests:
        print(f"  Testing: {label} …", end=" ", flush=True)
        result = run_test(label, method, url, **kwargs)
        passed = evaluate(result, expected)
        mark = "✅" if passed else "❌"
        got = str(result["status"]) if result["status"] else f"ERR"
        print(f"{mark}  got {got} (expected {expected})  [{result['elapsed_ms']} ms]")
        results.append(result)

    now_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    write_report(results, expectations, now_str)

    all_pass = all(evaluate(r, e) for r, e in zip(results, expectations))
    print(f"\n── Result ──────────────────────────────────────────")
    print(f"  {'ALL TESTS PASSED ✅' if all_pass else 'SOME TESTS FAILED ❌'}")
    print(f"  Report written to: {OUTPUT_PATH}\n")

    sys.exit(0 if all_pass else 1)


if __name__ == "__main__":
    main()
